
package pt.chequerefeicao.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChequeRefeicaoService", targetNamespace = "urn:pt:chequerefeicao:ws", wsdlLocation = "file:/C:/Users/Jo%C3%A3o%20Br%C3%A1s/workspace/chequerefeicao-ws/build/src/ChequeRefeicao.wsdl")
public class ChequeRefeicaoService
    extends Service
{

    private final static URL CHEQUEREFEICAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHEQUEREFEICAOSERVICE_EXCEPTION;
    private final static QName CHEQUEREFEICAOSERVICE_QNAME = new QName("urn:pt:chequerefeicao:ws", "ChequeRefeicaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Jo%C3%A3o%20Br%C3%A1s/workspace/chequerefeicao-ws/build/src/ChequeRefeicao.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHEQUEREFEICAOSERVICE_WSDL_LOCATION = url;
        CHEQUEREFEICAOSERVICE_EXCEPTION = e;
    }

    public ChequeRefeicaoService() {
        super(__getWsdlLocation(), CHEQUEREFEICAOSERVICE_QNAME);
    }

    public ChequeRefeicaoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHEQUEREFEICAOSERVICE_QNAME, features);
    }

    public ChequeRefeicaoService(URL wsdlLocation) {
        super(wsdlLocation, CHEQUEREFEICAOSERVICE_QNAME);
    }

    public ChequeRefeicaoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHEQUEREFEICAOSERVICE_QNAME, features);
    }

    public ChequeRefeicaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChequeRefeicaoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChequeRefeicaoPortType
     */
    @WebEndpoint(name = "ChequeRefeicaoPort")
    public ChequeRefeicaoPortType getChequeRefeicaoPort() {
        return super.getPort(new QName("urn:pt:chequerefeicao:ws", "ChequeRefeicaoPort"), ChequeRefeicaoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChequeRefeicaoPortType
     */
    @WebEndpoint(name = "ChequeRefeicaoPort")
    public ChequeRefeicaoPortType getChequeRefeicaoPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:pt:chequerefeicao:ws", "ChequeRefeicaoPort"), ChequeRefeicaoPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHEQUEREFEICAOSERVICE_EXCEPTION!= null) {
            throw CHEQUEREFEICAOSERVICE_EXCEPTION;
        }
        return CHEQUEREFEICAOSERVICE_WSDL_LOCATION;
    }

}
